# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.AliasDto do
  @moduledoc """
  Email alias representation
  """

  @derive [Poison.Encoder]
  defstruct [
    :"createdAt",
    :"emailAddress",
    :"id",
    :"inboxId",
    :"isVerified",
    :"maskedEmailAddress",
    :"name",
    :"updatedAt",
    :"useThreads",
    :"userId"
  ]

  @type t :: %__MODULE__{
    :"createdAt" => DateTime.t | nil,
    :"emailAddress" => String.t | nil,
    :"id" => String.t,
    :"inboxId" => String.t | nil,
    :"isVerified" => boolean() | nil,
    :"maskedEmailAddress" => String.t | nil,
    :"name" => String.t | nil,
    :"updatedAt" => DateTime.t | nil,
    :"useThreads" => boolean() | nil,
    :"userId" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.AliasDto do
  def decode(value, _options) do
    value
  end
end

