# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.AttachmentEntity do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"attachmentId",
    :"contentLength",
    :"contentType",
    :"createdAt",
    :"id",
    :"name",
    :"updatedAt",
    :"userId"
  ]

  @type t :: %__MODULE__{
    :"attachmentId" => String.t,
    :"contentLength" => integer() | nil,
    :"contentType" => String.t | nil,
    :"createdAt" => DateTime.t,
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"updatedAt" => DateTime.t,
    :"userId" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.AttachmentEntity do
  def decode(value, _options) do
    value
  end
end

