# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.AttachmentMetaData do
  @moduledoc """
  Meta data associated with an attachment. Attachments are stored as byte blobs so the meta data is stored separately.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"contentLength",
    :"contentType",
    :"id",
    :"name"
  ]

  @type t :: %__MODULE__{
    :"contentLength" => integer() | nil,
    :"contentType" => String.t | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.AttachmentMetaData do
  def decode(value, _options) do
    value
  end
end

