# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.BasicAuthOptions do
  @moduledoc """
  Basic Authentication options for webhooks. Will be used is present when calling webhook endpoints.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"username",
    :"password"
  ]

  @type t :: %__MODULE__{
    :"username" => String.t,
    :"password" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.BasicAuthOptions do
  def decode(value, _options) do
    value
  end
end

