# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.BounceRecipientProjection do
  @moduledoc """
  Bounced recipient
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"status",
    :"createdAt",
    :"sentEmailId",
    :"recipient",
    :"action"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"status" => String.t | nil,
    :"createdAt" => DateTime.t,
    :"sentEmailId" => String.t | nil,
    :"recipient" => String.t,
    :"action" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.BounceRecipientProjection do
  def decode(value, _options) do
    value
  end
end

