# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.BouncedRecipientDto do
  @moduledoc """
  Bounced recipient
  """

  @derive [Poison.Encoder]
  defstruct [
    :"createdAt",
    :"id",
    :"recipient",
    :"userId"
  ]

  @type t :: %__MODULE__{
    :"createdAt" => DateTime.t,
    :"id" => String.t | nil,
    :"recipient" => String.t,
    :"userId" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.BouncedRecipientDto do
  def decode(value, _options) do
    value
  end
end

