# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.BounceProjection do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"sender",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"sender" => String.t,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.BounceProjection do
  def decode(value, _options) do
    value
  end
end

