# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.BouncedRecipientDto do
  @moduledoc """
  Bounced recipient
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"userId",
    :"sentEmailId",
    :"recipient",
    :"diagnosticCode",
    :"action",
    :"status",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"userId" => String.t | nil,
    :"sentEmailId" => String.t | nil,
    :"recipient" => String.t,
    :"diagnosticCode" => String.t | nil,
    :"action" => String.t | nil,
    :"status" => String.t | nil,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.BouncedRecipientDto do
  def decode(value, _options) do
    value
  end
end

