# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.BulkSendEmailOptions do
  @moduledoc """
  Options for bulk sending an email from multiple addresses. See regular &#x60;sendEmail&#x60; methods for more information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"inboxIds",
    :"sendEmailOptions"
  ]

  @type t :: %__MODULE__{
    :"inboxIds" => [String.t] | nil,
    :"sendEmailOptions" => SendEmailOptions | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.BulkSendEmailOptions do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sendEmailOptions", :struct, MailSlurpAPI.Model.SendEmailOptions, options)
  end
end

