# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.Complaint do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"userId",
    :"eventType",
    :"mailSource",
    :"mailMessageId",
    :"complaintRecipient",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"userId" => String.t | nil,
    :"eventType" => String.t | nil,
    :"mailSource" => String.t | nil,
    :"mailMessageId" => String.t | nil,
    :"complaintRecipient" => String.t,
    :"createdAt" => DateTime.t,
    :"updatedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.Complaint do
  def decode(value, _options) do
    value
  end
end

