# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ConditionOption do
  @moduledoc """
  Options for matching emails in an inbox based on a condition such as &#x60;HAS_ATTACHMENTS&#x3D;TRUE&#x60;
  """

  @derive [Poison.Encoder]
  defstruct [
    :"condition",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"condition" => String.t,
    :"value" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ConditionOption do
  def decode(value, _options) do
    value
  end
end

