# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ConnectorDto do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"userId",
    :"connectorType",
    :"connectorAuthType",
    :"syncEnabled",
    :"syncScheduleType",
    :"syncInterval",
    :"imapHost",
    :"imapPort",
    :"imapUsername",
    :"imapPassword",
    :"imapSsl",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"userId" => String.t,
    :"connectorType" => String.t,
    :"connectorAuthType" => String.t,
    :"syncEnabled" => boolean(),
    :"syncScheduleType" => String.t,
    :"syncInterval" => integer() | nil,
    :"imapHost" => String.t | nil,
    :"imapPort" => integer() | nil,
    :"imapUsername" => String.t | nil,
    :"imapPassword" => String.t | nil,
    :"imapSsl" => boolean() | nil,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ConnectorDto do
  def decode(value, _options) do
    value
  end
end

