# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ConnectorSyncEventDto do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"connectorId",
    :"syncStatus",
    :"syncCount",
    :"message",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"connectorId" => String.t,
    :"syncStatus" => String.t,
    :"syncCount" => integer(),
    :"message" => String.t | nil,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ConnectorSyncEventDto do
  def decode(value, _options) do
    value
  end
end

