# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ContactDto do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"company",
    :"createdAt",
    :"emailAddresses",
    :"firstName",
    :"groupId",
    :"id",
    :"lastName",
    :"metaData",
    :"optOut",
    :"primaryEmailAddress",
    :"tags"
  ]

  @type t :: %__MODULE__{
    :"company" => String.t | nil,
    :"createdAt" => DateTime.t,
    :"emailAddresses" => [String.t],
    :"firstName" => String.t | nil,
    :"groupId" => String.t | nil,
    :"id" => String.t,
    :"lastName" => String.t | nil,
    :"metaData" => Map | nil,
    :"optOut" => boolean() | nil,
    :"primaryEmailAddress" => String.t | nil,
    :"tags" => [String.t]
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ContactDto do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metaData", :struct, MailSlurpAPI.Model.Map, options)
  end
end

