# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.CreateInboxDto do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"emailAddress",
    :"expiresAt",
    :"favourite",
    :"name",
    :"tags"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t | nil,
    :"emailAddress" => String.t | nil,
    :"expiresAt" => DateTime.t | nil,
    :"favourite" => boolean() | nil,
    :"name" => String.t | nil,
    :"tags" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.CreateInboxDto do
  def decode(value, _options) do
    value
  end
end

