# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.CreateInboxRulesetOptions do
  @moduledoc """
  Options for creating inbox rulesets. Inbox rulesets can be used to block, allow, filter, or forward emails when sending or receiving using the inbox.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"scope",
    :"action",
    :"target"
  ]

  @type t :: %__MODULE__{
    :"scope" => String.t,
    :"action" => String.t,
    :"target" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.CreateInboxRulesetOptions do
  def decode(value, _options) do
    value
  end
end

