# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.CreateTrackingPixelOptions do
  @moduledoc """
  Options for creating a tracking pixel for email open tracking
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"recipient"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"recipient" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.CreateTrackingPixelOptions do
  def decode(value, _options) do
    value
  end
end

