# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.CreateDomainOptions do
  @moduledoc """
  Options for creating a domain to use with MailSlurp. You must have ownership access to this domain in order to verify it. Domains will not function correctly until the domain has been verified. See https://www.mailslurp.com/guides/custom-domains for help. Domains can be either &#x60;HTTP&#x60; or &#x60;SMTP&#x60; type. The type of domain determines which inboxes can be used with it. &#x60;SMTP&#x60; inboxes use a mail server running &#x60;mx.mailslurp.com&#x60; while &#x60;HTTP&#x60; inboxes are handled by AWS SES.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"domain",
    :"description",
    :"createdCatchAllInbox",
    :"domainType"
  ]

  @type t :: %__MODULE__{
    :"domain" => String.t,
    :"description" => String.t | nil,
    :"createdCatchAllInbox" => boolean() | nil,
    :"domainType" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.CreateDomainOptions do
  def decode(value, _options) do
    value
  end
end

