# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.CreateEmergencyAddressOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"customerName",
    :"address1",
    :"city",
    :"region",
    :"postalCode",
    :"isoCountryCode",
    :"displayName"
  ]

  @type t :: %__MODULE__{
    :"customerName" => String.t,
    :"address1" => String.t,
    :"city" => String.t,
    :"region" => String.t,
    :"postalCode" => String.t,
    :"isoCountryCode" => String.t,
    :"displayName" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.CreateEmergencyAddressOptions do
  def decode(value, _options) do
    value
  end
end

