# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.CreateConnectorImapOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"host",
    :"port",
    :"username",
    :"password",
    :"useSSL"
  ]

  @type t :: %__MODULE__{
    :"host" => String.t,
    :"port" => integer(),
    :"username" => String.t,
    :"password" => String.t,
    :"useSSL" => boolean()
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.CreateConnectorImapOptions do
  def decode(value, _options) do
    value
  end
end

