# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.CreateInboxDto do
  @moduledoc """
  Options for creating an inbox. An inbox has a real email address that can send and receive emails. Inboxes can be permanent or expire at a given time. They can use a custom email address (by verifying your own domain) or a randomly assigned email ending in either &#x60;mailslurp.com&#x60; or if &#x60;useDomainPool&#x60; is enabled then ending in a similar domains such as &#x60;mailslurp.xyz&#x60; (selected at random). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"allowTeamAccess",
    :"description",
    :"emailAddress",
    :"expiresAt",
    :"expiresIn",
    :"favourite",
    :"name",
    :"tags",
    :"useDomainPool"
  ]

  @type t :: %__MODULE__{
    :"allowTeamAccess" => boolean() | nil,
    :"description" => String.t | nil,
    :"emailAddress" => String.t | nil,
    :"expiresAt" => DateTime.t | nil,
    :"expiresIn" => integer() | nil,
    :"favourite" => boolean() | nil,
    :"name" => String.t | nil,
    :"tags" => [String.t] | nil,
    :"useDomainPool" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.CreateInboxDto do
  def decode(value, _options) do
    value
  end
end

