# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.DeliveryStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"userId",
    :"sentId",
    :"remoteMtaIp",
    :"inboxId",
    :"reportingMta",
    :"recipients",
    :"smtpResponse",
    :"processingTimeMillis",
    :"received",
    :"subject",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"userId" => String.t,
    :"sentId" => String.t | nil,
    :"remoteMtaIp" => String.t | nil,
    :"inboxId" => String.t | nil,
    :"reportingMta" => String.t | nil,
    :"recipients" => [String.t] | nil,
    :"smtpResponse" => String.t | nil,
    :"processingTimeMillis" => integer() | nil,
    :"received" => DateTime.t | nil,
    :"subject" => String.t | nil,
    :"createdAt" => DateTime.t,
    :"updatedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.DeliveryStatus do
  def decode(value, _options) do
    value
  end
end

