# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.DnsLookupOptions do
  @moduledoc """
  Options for DNS query. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"hostname",
    :"omitFinalDNSDot",
    :"recordTypes"
  ]

  @type t :: %__MODULE__{
    :"hostname" => String.t | nil,
    :"omitFinalDNSDot" => boolean() | nil,
    :"recordTypes" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.DnsLookupOptions do
  def decode(value, _options) do
    value
  end
end

