# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.DomainDto do
  @moduledoc """
  Domain plus verification records and status
  """

  @derive [Poison.Encoder]
  defstruct [
    :"catchAllInboxId",
    :"createdAt",
    :"dkimTokens",
    :"domain",
    :"domainNameRecords",
    :"domainType",
    :"id",
    :"isVerified",
    :"updatedAt",
    :"userId",
    :"verificationToken"
  ]

  @type t :: %__MODULE__{
    :"catchAllInboxId" => String.t | nil,
    :"createdAt" => DateTime.t,
    :"dkimTokens" => [String.t] | nil,
    :"domain" => String.t | nil,
    :"domainNameRecords" => [DomainNameRecord] | nil,
    :"domainType" => String.t | nil,
    :"id" => String.t,
    :"isVerified" => boolean() | nil,
    :"updatedAt" => DateTime.t,
    :"userId" => String.t,
    :"verificationToken" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.DomainDto do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"domainNameRecords", :list, MailSlurpAPI.Model.DomainNameRecord, options)
  end
end

