# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.EmailHtmlDto do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"subject",
    :"body"
  ]

  @type t :: %__MODULE__{
    :"subject" => String.t | nil,
    :"body" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.EmailHtmlDto do
  def decode(value, _options) do
    value
  end
end

