# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ForwardEmailOptions do
  @moduledoc """
  Options for forwarding an email
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bcc",
    :"cc",
    :"from",
    :"subject",
    :"to"
  ]

  @type t :: %__MODULE__{
    :"bcc" => [String.t] | nil,
    :"cc" => [String.t] | nil,
    :"from" => String.t | nil,
    :"subject" => String.t | nil,
    :"to" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ForwardEmailOptions do
  def decode(value, _options) do
    value
  end
end

