# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.GenerateBimiRecordOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"domain",
    :"version",
    :"logoUrl",
    :"vmcUrl"
  ]

  @type t :: %__MODULE__{
    :"domain" => String.t,
    :"version" => String.t,
    :"logoUrl" => String.t,
    :"vmcUrl" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.GenerateBimiRecordOptions do
  def decode(value, _options) do
    value
  end
end

