# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.GravatarUrl do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"url",
    :"hash"
  ]

  @type t :: %__MODULE__{
    :"url" => String.t,
    :"hash" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.GravatarUrl do
  def decode(value, _options) do
    value
  end
end

