# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.Inbox do
  @moduledoc """
  Representation of a MailSlurp inbox. An inbox has an ID and a real email address. Emails can be sent to or from this email address. Use the &#x60;EmailController&#x60; or the &#x60;InboxController&#x60; methods to send and receive emails and attachments.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"createdAt",
    :"description",
    :"emailAddress",
    :"expiresAt",
    :"favourite",
    :"id",
    :"name",
    :"readOnly",
    :"tags",
    :"teamAccess",
    :"userId"
  ]

  @type t :: %__MODULE__{
    :"createdAt" => DateTime.t | nil,
    :"description" => String.t | nil,
    :"emailAddress" => String.t | nil,
    :"expiresAt" => String.t | nil,
    :"favourite" => boolean() | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"readOnly" => boolean() | nil,
    :"tags" => [String.t] | nil,
    :"teamAccess" => boolean() | nil,
    :"userId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.Inbox do
  def decode(value, _options) do
    value
  end
end

