# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.InboxRulesetDto do
  @moduledoc """
  Rules for inbox
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"inboxId",
    :"scope",
    :"action",
    :"target",
    :"handler",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"inboxId" => String.t,
    :"scope" => String.t,
    :"action" => String.t,
    :"target" => String.t,
    :"handler" => String.t,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.InboxRulesetDto do
  def decode(value, _options) do
    value
  end
end

