# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.InboxIdItem do
  @moduledoc """
  Inbox ID and email address pair
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"emailAddress"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"emailAddress" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.InboxIdItem do
  def decode(value, _options) do
    value
  end
end

