# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.InboxForwarderTestOptions do
  @moduledoc """
  Options for testing an inbox forwarder against a value
  """

  @derive [Poison.Encoder]
  defstruct [
    :"testValue"
  ]

  @type t :: %__MODULE__{
    :"testValue" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.InboxForwarderTestOptions do
  def decode(value, _options) do
    value
  end
end

