# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.InboxReplierDto do
  @moduledoc """
  Inbox replier. Will automatically reply to inbound emails that match given field for an inbox.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"inboxId",
    :"name",
    :"field",
    :"match",
    :"replyTo",
    :"subject",
    :"from",
    :"charset",
    :"isHTML",
    :"templateId",
    :"templateVariables",
    :"ignoreReplyTo",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"inboxId" => String.t,
    :"name" => String.t | nil,
    :"field" => String.t,
    :"match" => String.t,
    :"replyTo" => String.t | nil,
    :"subject" => String.t | nil,
    :"from" => String.t | nil,
    :"charset" => String.t | nil,
    :"isHTML" => boolean(),
    :"templateId" => String.t | nil,
    :"templateVariables" => %{optional(String.t) => Map} | nil,
    :"ignoreReplyTo" => boolean(),
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.InboxReplierDto do
  def decode(value, _options) do
    value
  end
end

