# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.InboxExistsDto do
  @moduledoc """
  Result of email exists query
  """

  @derive [Poison.Encoder]
  defstruct [
    :"exists"
  ]

  @type t :: %__MODULE__{
    :"exists" => boolean()
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.InboxExistsDto do
  def decode(value, _options) do
    value
  end
end

