# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.MissedEmail do
  @moduledoc """
  Missed email
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"userId",
    :"subject",
    :"bodyExcerpt",
    :"attachmentCount",
    :"from",
    :"to",
    :"cc",
    :"bcc",
    :"inboxIds",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"userId" => String.t | nil,
    :"subject" => String.t | nil,
    :"bodyExcerpt" => String.t | nil,
    :"attachmentCount" => integer(),
    :"from" => String.t | nil,
    :"to" => [String.t],
    :"cc" => [String.t],
    :"bcc" => [String.t],
    :"inboxIds" => [String.t],
    :"createdAt" => DateTime.t,
    :"updatedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.MissedEmail do
  def decode(value, _options) do
    value
  end
end

