# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.OrganizationInboxProjection do
  @moduledoc """
  Organization team inbox
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"createdAt",
    :"name",
    :"emailAddress",
    :"favourite",
    :"tags",
    :"teamAccess",
    :"inboxType",
    :"readOnly"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"createdAt" => DateTime.t,
    :"name" => String.t | nil,
    :"emailAddress" => String.t | nil,
    :"favourite" => boolean(),
    :"tags" => [String.t] | nil,
    :"teamAccess" => boolean(),
    :"inboxType" => String.t | nil,
    :"readOnly" => boolean()
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.OrganizationInboxProjection do
  def decode(value, _options) do
    value
  end
end

