# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.Pageable do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"offset",
    :"pageNumber",
    :"pageSize",
    :"paged",
    :"sort",
    :"unpaged"
  ]

  @type t :: %__MODULE__{
    :"offset" => integer() | nil,
    :"pageNumber" => integer() | nil,
    :"pageSize" => integer() | nil,
    :"paged" => boolean() | nil,
    :"sort" => Sort | nil,
    :"unpaged" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.Pageable do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sort", :struct, MailSlurpAPI.Model.Sort, options)
  end
end

