# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.PhoneNumberDto do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"userId",
    :"complianceAddress",
    :"emergencyAddress",
    :"phoneNumber",
    :"phoneCountry",
    :"phonePlan",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"userId" => String.t,
    :"complianceAddress" => String.t | nil,
    :"emergencyAddress" => String.t | nil,
    :"phoneNumber" => String.t,
    :"phoneCountry" => String.t,
    :"phonePlan" => String.t,
    :"createdAt" => DateTime.t,
    :"updatedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.PhoneNumberDto do
  def decode(value, _options) do
    value
  end
end

