# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ReplyToEmailOptions do
  @moduledoc """
  Options for replying to email with API
  """

  @derive [Poison.Encoder]
  defstruct [
    :"body",
    :"isHTML",
    :"from",
    :"replyTo",
    :"charset",
    :"attachments",
    :"templateVariables",
    :"template",
    :"sendStrategy",
    :"useInboxName"
  ]

  @type t :: %__MODULE__{
    :"body" => String.t,
    :"isHTML" => boolean(),
    :"from" => String.t | nil,
    :"replyTo" => String.t | nil,
    :"charset" => String.t | nil,
    :"attachments" => [String.t] | nil,
    :"templateVariables" => %{optional(String.t) => Map} | nil,
    :"template" => String.t | nil,
    :"sendStrategy" => String.t | nil,
    :"useInboxName" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ReplyToEmailOptions do
  def decode(value, _options) do
    value
  end
end

