# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ReplyForSms do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reply"
  ]

  @type t :: %__MODULE__{
    :"reply" => SentSmsDto | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ReplyForSms do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"reply", :struct, MailSlurpAPI.Model.SentSmsDto, options)
  end
end

