# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.SendSmtpEnvelopeOptions do
  @moduledoc """
  Options for the email envelope
  """

  @derive [Poison.Encoder]
  defstruct [
    :"rcptTo",
    :"mailFrom",
    :"data"
  ]

  @type t :: %__MODULE__{
    :"rcptTo" => [String.t],
    :"mailFrom" => String.t,
    :"data" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.SendSmtpEnvelopeOptions do
  def decode(value, _options) do
    value
  end
end

