# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.Sender do
  @moduledoc """
  Sender object containing from email address and from personal name if provided in address
  """

  @derive [Poison.Encoder]
  defstruct [
    :"rawValue",
    :"emailAddress",
    :"name"
  ]

  @type t :: %__MODULE__{
    :"rawValue" => String.t,
    :"emailAddress" => String.t,
    :"name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.Sender do
  def decode(value, _options) do
    value
  end
end

