# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.Sender do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"emailAddress",
    :"name",
    :"rawValue"
  ]

  @type t :: %__MODULE__{
    :"emailAddress" => String.t,
    :"name" => String.t | nil,
    :"rawValue" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.Sender do
  def decode(value, _options) do
    value
  end
end

