# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.SetInboxFavouritedOptions do
  @moduledoc """
  Options for setting inbox favourite state
  """

  @derive [Poison.Encoder]
  defstruct [
    :"state"
  ]

  @type t :: %__MODULE__{
    :"state" => boolean()
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.SetInboxFavouritedOptions do
  def decode(value, _options) do
    value
  end
end

