# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.SimpleSendEmailOptions do
  @moduledoc """
  Simplified send email options
  """

  @derive [Poison.Encoder]
  defstruct [
    :"senderId",
    :"to",
    :"body",
    :"subject"
  ]

  @type t :: %__MODULE__{
    :"senderId" => String.t | nil,
    :"to" => String.t,
    :"body" => String.t | nil,
    :"subject" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.SimpleSendEmailOptions do
  def decode(value, _options) do
    value
  end
end

