# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.SmsMessage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"userId",
    :"phoneNumber",
    :"fromNumber",
    :"body",
    :"read",
    :"sid",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"userId" => String.t,
    :"phoneNumber" => String.t,
    :"fromNumber" => String.t,
    :"body" => String.t,
    :"read" => boolean(),
    :"sid" => String.t,
    :"createdAt" => DateTime.t,
    :"updatedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.SmsMessage do
  def decode(value, _options) do
    value
  end
end

