# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.SmsReplyOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"body"
  ]

  @type t :: %__MODULE__{
    :"body" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.SmsReplyOptions do
  def decode(value, _options) do
    value
  end
end

