# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.Sort do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"empty",
    :"unsorted",
    :"sorted"
  ]

  @type t :: %__MODULE__{
    :"empty" => boolean() | nil,
    :"unsorted" => boolean() | nil,
    :"sorted" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.Sort do
  def decode(value, _options) do
    value
  end
end

