# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.TemplateProjection do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"id",
    :"variables",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"id" => String.t,
    :"variables" => [String.t],
    :"createdAt" => DateTime.t,
    :"updatedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.TemplateProjection do
  def decode(value, _options) do
    value
  end
end

