# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.TestNewInboxRulesetOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"inboxRulesetTestOptions",
    :"createInboxRulesetOptions"
  ]

  @type t :: %__MODULE__{
    :"inboxRulesetTestOptions" => InboxRulesetTestOptions,
    :"createInboxRulesetOptions" => CreateInboxRulesetOptions
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.TestNewInboxRulesetOptions do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"inboxRulesetTestOptions", :struct, MailSlurpAPI.Model.InboxRulesetTestOptions, options)
    |> deserialize(:"createInboxRulesetOptions", :struct, MailSlurpAPI.Model.CreateInboxRulesetOptions, options)
  end
end

