# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.TestNewInboxForwarderOptions do
  @moduledoc """
  Options for testing new inbox forwarder rules
  """

  @derive [Poison.Encoder]
  defstruct [
    :"inboxForwarderTestOptions",
    :"createInboxForwarderOptions"
  ]

  @type t :: %__MODULE__{
    :"inboxForwarderTestOptions" => InboxForwarderTestOptions,
    :"createInboxForwarderOptions" => CreateInboxForwarderOptions
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.TestNewInboxForwarderOptions do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"inboxForwarderTestOptions", :struct, MailSlurpAPI.Model.InboxForwarderTestOptions, options)
    |> deserialize(:"createInboxForwarderOptions", :struct, MailSlurpAPI.Model.CreateInboxForwarderOptions, options)
  end
end

