# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ThreadProjection do
  @moduledoc """
  A thread is a message thread created for a message received by an alias
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"id",
    :"subject",
    :"userId",
    :"inboxId",
    :"to",
    :"updatedAt",
    :"bcc",
    :"cc",
    :"createdAt",
    :"aliasId"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"id" => String.t,
    :"subject" => String.t | nil,
    :"userId" => String.t,
    :"inboxId" => String.t,
    :"to" => [String.t],
    :"updatedAt" => DateTime.t,
    :"bcc" => [String.t] | nil,
    :"cc" => [String.t] | nil,
    :"createdAt" => DateTime.t,
    :"aliasId" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ThreadProjection do
  def decode(value, _options) do
    value
  end
end

