# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.TrackingPixelDto do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"createdAt",
    :"html",
    :"id",
    :"inboxId",
    :"recipient",
    :"seen",
    :"seenAt",
    :"sentEmailId",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"createdAt" => DateTime.t,
    :"html" => String.t,
    :"id" => String.t,
    :"inboxId" => String.t | nil,
    :"recipient" => String.t | nil,
    :"seen" => boolean(),
    :"seenAt" => DateTime.t | nil,
    :"sentEmailId" => String.t | nil,
    :"url" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.TrackingPixelDto do
  def decode(value, _options) do
    value
  end
end

