# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.UnknownMissedEmailProjection do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"from",
    :"createdAt",
    :"subject",
    :"to"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"from" => String.t | nil,
    :"createdAt" => DateTime.t,
    :"subject" => String.t | nil,
    :"to" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.UnknownMissedEmailProjection do
  def decode(value, _options) do
    value
  end
end

