# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.UnseenErrorCountDto do
  @moduledoc """
  Number of unseen errors
  """

  @derive [Poison.Encoder]
  defstruct [
    :"count"
  ]

  @type t :: %__MODULE__{
    :"count" => integer()
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.UnseenErrorCountDto do
  def decode(value, _options) do
    value
  end
end

