# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.UpdateInboxOptions do
  @moduledoc """
  Options for updating inbox properties
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"description",
    :"tags",
    :"expiresAt",
    :"favourite"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"description" => String.t | nil,
    :"tags" => [String.t] | nil,
    :"expiresAt" => DateTime.t | nil,
    :"favourite" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.UpdateInboxOptions do
  def decode(value, _options) do
    value
  end
end

