# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.UpdateDomainOptions do
  @moduledoc """
  Options for creating a domain to use with MailSlurp. You must have ownership access to this domain in order to verify it. Domains will not functionally currently until the domain has been verified. See https://www.mailslurp.com/guides/custom-domains for help.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"catchAllInboxId"
  ]

  @type t :: %__MODULE__{
    :"catchAllInboxId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.UpdateDomainOptions do
  def decode(value, _options) do
    value
  end
end

