# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.UpdateGroupContacts do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"contactIds"
  ]

  @type t :: %__MODULE__{
    :"contactIds" => [String.t]
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.UpdateGroupContacts do
  def decode(value, _options) do
    value
  end
end

