# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.UploadAttachmentOptions do
  @moduledoc """
  Options for uploading files for attachments. When sending emails with the API that require attachments first upload each attachment. Then use the returned attachment ID in your &#x60;SendEmailOptions&#x60; when sending an email. This way you can use attachments multiple times once they have been uploaded.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"contentType",
    :"filename",
    :"base64Contents"
  ]

  @type t :: %__MODULE__{
    :"contentType" => String.t | nil,
    :"filename" => String.t | nil,
    :"base64Contents" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.UploadAttachmentOptions do
  def decode(value, _options) do
    value
  end
end

