# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.UserDto do
  @moduledoc """
  Representation a user&#39;s account
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"apiKey",
    :"emailAddress",
    :"emailAddressMd5",
    :"created",
    :"userType",
    :"organization",
    :"verified",
    :"hasPassword",
    :"isFrozen",
    :"addNewContacts",
    :"ssoProvider",
    :"customerId",
    :"hasOnboarded",
    :"imapUsername",
    :"imapPassword",
    :"smtpUsername",
    :"smtpPassword"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"apiKey" => String.t,
    :"emailAddress" => String.t,
    :"emailAddressMd5" => String.t,
    :"created" => DateTime.t | nil,
    :"userType" => String.t | nil,
    :"organization" => String.t | nil,
    :"verified" => String.t | nil,
    :"hasPassword" => boolean(),
    :"isFrozen" => boolean(),
    :"addNewContacts" => boolean() | nil,
    :"ssoProvider" => String.t | nil,
    :"customerId" => String.t | nil,
    :"hasOnboarded" => boolean() | nil,
    :"imapUsername" => String.t | nil,
    :"imapPassword" => String.t | nil,
    :"smtpUsername" => String.t | nil,
    :"smtpPassword" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.UserDto do
  def decode(value, _options) do
    value
  end
end

