# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.UserInfoDto do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"emailAddress",
    :"accountState",
    :"subscriptionType",
    :"accountType",
    :"createdAt"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"emailAddress" => String.t,
    :"accountState" => String.t,
    :"subscriptionType" => String.t | nil,
    :"accountType" => String.t,
    :"createdAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.UserInfoDto do
  def decode(value, _options) do
    value
  end
end

