# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ValidateEmailAddressListOptions do
  @moduledoc """
  Options for validating a list of email addresses
  """

  @derive [Poison.Encoder]
  defstruct [
    :"emailAddressList"
  ]

  @type t :: %__MODULE__{
    :"emailAddressList" => [String.t]
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ValidateEmailAddressListOptions do
  def decode(value, _options) do
    value
  end
end

