# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.ValidationDto do
  @moduledoc """
  Response object for email validation operation
  """

  @derive [Poison.Encoder]
  defstruct [
    :"emailId",
    :"html"
  ]

  @type t :: %__MODULE__{
    :"emailId" => String.t,
    :"html" => HtmlValidationResult
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.ValidationDto do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"html", :struct, MailSlurpAPI.Model.HtmlValidationResult, options)
  end
end

