# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.VerifyWebhookSignatureOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"messageId",
    :"signature"
  ]

  @type t :: %__MODULE__{
    :"messageId" => String.t,
    :"signature" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.VerifyWebhookSignatureOptions do
  def decode(value, _options) do
    value
  end
end

