# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.WaitForSingleSmsOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"phoneNumberId",
    :"timeout",
    :"unreadOnly",
    :"before",
    :"since",
    :"sortDirection",
    :"delay"
  ]

  @type t :: %__MODULE__{
    :"phoneNumberId" => String.t,
    :"timeout" => integer(),
    :"unreadOnly" => boolean() | nil,
    :"before" => DateTime.t | nil,
    :"since" => DateTime.t | nil,
    :"sortDirection" => String.t | nil,
    :"delay" => integer() | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.WaitForSingleSmsOptions do
  def decode(value, _options) do
    value
  end
end

