# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.WebhookDeliveryStatusPayload do
  @moduledoc """
  DELIVERY_STATUS webhook payload. Sent to your webhook url endpoint via HTTP POST when an email delivery status is created. This could be a successful delivery or a delivery failure.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"messageId",
    :"webhookId",
    :"eventName",
    :"webhookName",
    :"id",
    :"userId",
    :"sentId",
    :"remoteMtaIp",
    :"inboxId",
    :"reportingMta",
    :"recipients",
    :"smtpResponse",
    :"smtpStatusCode",
    :"processingTimeMillis",
    :"received",
    :"subject"
  ]

  @type t :: %__MODULE__{
    :"messageId" => String.t,
    :"webhookId" => String.t,
    :"eventName" => String.t,
    :"webhookName" => String.t | nil,
    :"id" => String.t,
    :"userId" => String.t,
    :"sentId" => String.t | nil,
    :"remoteMtaIp" => String.t | nil,
    :"inboxId" => String.t | nil,
    :"reportingMta" => String.t | nil,
    :"recipients" => [String.t] | nil,
    :"smtpResponse" => String.t | nil,
    :"smtpStatusCode" => integer() | nil,
    :"processingTimeMillis" => integer() | nil,
    :"received" => DateTime.t | nil,
    :"subject" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.WebhookDeliveryStatusPayload do
  def decode(value, _options) do
    value
  end
end

