# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.WebhookNewEmailPayload do
  @moduledoc """
  NEW_EMAIL webhook payload
  """

  @derive [Poison.Encoder]
  defstruct [
    :"attachmentMetaDatas",
    :"bcc",
    :"cc",
    :"createdAt",
    :"emailId",
    :"eventName",
    :"from",
    :"inboxId",
    :"messageId",
    :"subject",
    :"to",
    :"webhookId",
    :"webhookName"
  ]

  @type t :: %__MODULE__{
    :"attachmentMetaDatas" => [AttachmentMetaData] | nil,
    :"bcc" => [String.t] | nil,
    :"cc" => [String.t] | nil,
    :"createdAt" => DateTime.t | nil,
    :"emailId" => String.t | nil,
    :"eventName" => String.t | nil,
    :"from" => String.t | nil,
    :"inboxId" => String.t | nil,
    :"messageId" => String.t | nil,
    :"subject" => String.t | nil,
    :"to" => [String.t] | nil,
    :"webhookId" => String.t | nil,
    :"webhookName" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.WebhookNewEmailPayload do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"attachmentMetaDatas", :list, MailSlurpAPI.Model.AttachmentMetaData, options)
  end
end

