# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.WebhookHeaders do
  @moduledoc """
  Webhook HTTP headers to include with each request from MailSlurp to your server
  """

  @derive [Poison.Encoder]
  defstruct [
    :"headers"
  ]

  @type t :: %__MODULE__{
    :"headers" => [WebhookHeaderNameValue]
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.WebhookHeaders do
  import MailSlurpAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"headers", :list, MailSlurpAPI.Model.WebhookHeaderNameValue, options)
  end
end

