# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.WebhookTestRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"headers",
    :"method",
    :"payload",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"headers" => %{optional(String.t) => String.t},
    :"method" => String.t,
    :"payload" => String.t | nil,
    :"url" => String.t
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.WebhookTestRequest do
  def decode(value, _options) do
    value
  end
end

