# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MailSlurpAPI.Model.WebhookEmailReadPayload do
  @moduledoc """
  EMAIL_READ webhook payload. Sent to your webhook url endpoint via HTTP POST when an email is read. This happens when an email is requested in full from the API or a user views the email in the dashboard.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"createdAt",
    :"emailId",
    :"emailIsRead",
    :"eventName",
    :"inboxId",
    :"messageId",
    :"webhookId",
    :"webhookName"
  ]

  @type t :: %__MODULE__{
    :"createdAt" => DateTime.t | nil,
    :"emailId" => String.t | nil,
    :"emailIsRead" => boolean() | nil,
    :"eventName" => String.t | nil,
    :"inboxId" => String.t | nil,
    :"messageId" => String.t | nil,
    :"webhookId" => String.t | nil,
    :"webhookName" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MailSlurpAPI.Model.WebhookEmailReadPayload do
  def decode(value, _options) do
    value
  end
end

